# Generated by Django 3.0.6 on 2020-05-28 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=10)),
                ('fax', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('raison_sociale', models.CharField(max_length=30, verbose_name='Raison Sociale')),
                ('siren', models.CharField(max_length=30)),
                ('code_ape', models.CharField(max_length=30, verbose_name='Code APE')),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=10)),
                ('fax', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('duree_deplacement', models.IntegerField(verbose_name='Durée de déplacement')),
                ('distance_km', models.IntegerField(verbose_name='Distance en km')),
                ('numero_agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitePPE.Agence', verbose_name='Agence')),
            ],
        ),
        migrations.CreateModel(
            name='Controler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.IntegerField(verbose_name='Numéro de série')),
                ('numero_intervention', models.IntegerField(verbose_name="Numéro d'intervention")),
                ('temps_passee', models.CharField(max_length=30, verbose_name='Temps passées')),
                ('commentaires', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FamilleProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TypeContrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delai_intervention', models.CharField(max_length=50, verbose_name="Délai d'intervention")),
                ('taux_applicable', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux applicable')),
            ],
        ),
        migrations.CreateModel(
            name='TypeMateriel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('code_famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitePPE.FamilleProduit')),
            ],
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('adresse', models.TextField()),
                ('date_embauche', models.DateTimeField(verbose_name="Date d'embauche")),
                ('telephone', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=30)),
                ('date_obtention', models.DateTimeField(verbose_name="Date d'obtention")),
                ('numero_agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitePPE.Agence')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_de_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente')),
                ('date_de_vente', models.DateTimeField(verbose_name='Date de la vente')),
                ('date_installation', models.DateTimeField(verbose_name="Date de l'installation")),
                ('emplacement', models.CharField(max_length=50)),
                ('type_materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitePPE.TypeMateriel')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField(verbose_name='Date de la visite')),
                ('heure_visite', models.TimeField(verbose_name='Heure de la visite')),
                ('statut', models.BooleanField(default=False)),
                ('matricule_technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitePPE.Technicien', verbose_name='Technicien')),
                ('numero_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitePPE.Client', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='ContratMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signature', models.DateTimeField(verbose_name='Date de la signature')),
                ('date_echance', models.DateTimeField(verbose_name='Date Echeance')),
                ('numero_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitePPE.Client')),
                ('type_contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitePPE.TypeContrat')),
            ],
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('adresse', models.TextField()),
                ('date_embauche', models.DateTimeField(verbose_name="Date d'embauche")),
                ('code_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitePPE.Region')),
            ],
        ),
        migrations.AddField(
            model_name='agence',
            name='code_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitePPE.Region'),
        ),
    ]
