# Generated by Django 3.0.6 on 2020-05-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitePPE', '0003_auto_20200528_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervention',
            options={'ordering': ['date_visite', 'heure_visite']},
        ),
    ]
