# Generated by Django 3.0.6 on 2020-06-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitePPE', '0005_assistant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratmaintenance',
            name='date_echance',
            field=models.DateField(verbose_name='Date Echeance'),
        ),
        migrations.AlterField(
            model_name='contratmaintenance',
            name='date_signature',
            field=models.DateField(verbose_name='Date de la signature'),
        ),
        migrations.AlterField(
            model_name='contratmaintenance',
            name='numero_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitePPE.Client', verbose_name='Client'),
        ),
    ]
